#!/usr/bin/env node

const title = "Try Partial Lenses with KLIPSE"
const icon = "https://avatars1.githubusercontent.com/u/17234211"
const github = "https://github.com/calmm-js/partial.lenses"
const site = "https://calmm-js.github.io/partial.lenses/"
const blob = `${github}/blob/master/`
const hljsStyle = "googlecode"

const I = require("infestines")
const R = require("ramda")
const fs = require("fs")

const marked = require("marked")

marked.setOptions({
  renderer: new marked.Renderer(),
  gfm: true,
  tables: true,
  breaks: false,
  pedantic: false,
  sanitize: false,
  smartLists: true,
  smartypants: false
})

const esc = R.replace(/[-\[\]{}()*+?.,\\^$|#\s]/g, "\\$&")

const body = I.seq(
  fs.readFileSync("README.md"),
  R.toString,
  R.replace(/([^ ])\bconst\b/g, "$1var"),
  R.replace(/\/\/ .*/g, ""),
  R.replace(/\[([^\]]*)\]\(\.\/([^)]*)\)/g, `[$1](${blob}$2)`),
  R.replace(new RegExp(esc(`[▶](${site}#`) + "([a-zA-Z-]*)" + esc(")"), "g"),
            `[■](${github}#$1)`),
  R.replace(new RegExp(esc(site), "g"), ""),
  marked,
  R.replace(/<code class="lang-([a-z]*)">/g,
            '<code class="hljs lang-$1\">'))

fs.writeFileSync("docs/index.html",
`<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>${title}</title>
    ${icon &&
      `<link rel="icon" href="${icon}">`}
    <link rel="stylesheet" type="text/css" href="github.css">
    ${hljsStyle &&
      `<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/styles/${hljsStyle}.min.css">`}
    <link rel="stylesheet" type="text/css" href="https://storage.googleapis.com/app.klipse.tech/css/codemirror.css">
    <link rel="stylesheet" type="text/css" href="styles.css">
    <script type="text/javascript">startTime = Date.now()</script>
    <script type="text/javascript" src="start.js" async></script>
  </head>
  <body class="markdown-body">
    <div class="loading-message">
      Please wait... The interactive code snippets on this page take a moment to load.
    </div>
    <div class="menu">
      <div class="menu-overlay"></div>
      <div class="menu-body">
        <div class="hamburger">≡</div>
        <div class="menu-contents"></div>
      </div>
    </div>
    <p>
      All the code snippets on this page are <b>live</b> and <b>interactive</b>
      powered by the <a href="https://github.com/viebel/klipse">klipse
      plugin</a>.
    <p>
    <hr>
    ${body}
    <div class="loading-hidden">
      <pre><code class="hljs lang-js">document.querySelector('.loading-message').className = "loading-hidden"
ga && ga('send', 'event', 'completed', 'load', Math.round((Date.now() - startTime)/1000))
      </code></pre>
    </div>
  </body>
</html>`)
