#!/usr/bin/env node

const title = "Try Partial Lenses with KLIPSE"
const icon = "https://avatars1.githubusercontent.com/u/17234211"
const github = "https://github.com/calmm-js/partial.lenses"
const blob = `${github}/blob/master/`
const hljsStyle = "googlecode"
const gaid = "UA-52808982-2"

const I = require("infestines")
const R = require("ramda")
const fs = require("fs")

const marked = require("marked")

marked.setOptions({
  renderer: new marked.Renderer(),
  gfm: true,
  tables: true,
  breaks: false,
  pedantic: false,
  sanitize: false,
  smartLists: true,
  smartypants: false
})

const body = I.seq(
  fs.readFileSync("README.md"),
  R.toString,
  R.replace(/([^ ])\bconst\b/g, "$1var"),
  R.replace(/\/\/ .*/g, ""),
  R.replace(/\[([^\]]*)\]\(\.\/([^)]*)\)/g, `[$1](${blob}$2)`),
  R.replace(/\[▶\]\(https:\/\/calmm-js\.github\.io\/partial\.lenses\/\#([a-zA-Z-]*)\)/g,
            `[■](${github}#$1)`),
  marked,
  R.replace(/<code class="lang-([a-z]*)">/g,
            '<code class="hljs lang-$1\">'))

fs.writeFileSync("docs/index.html",
`<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>${title}</title>
    ${icon &&
      `<link rel="icon" href="${icon}">`}
    <link rel="stylesheet" type="text/css" href="github.css">
    ${hljsStyle &&
      `<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/styles/${hljsStyle}.min.css">`}
    <link rel="stylesheet" type="text/css" href="https://storage.googleapis.com/app.klipse.tech/css/codemirror.css">
    <link rel="stylesheet" type="text/css" href="styles.css">
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', '${gaid}', 'auto');
      ga('send', 'pageview');
    </script>
    <script type="text/javascript" src="start.js" async></script>
  </head>
  <body class="markdown-body">
    <p>
      All the code snippets on this page are <b>live</b> and <b>interactive</b>
      powered by the <a href="https://github.com/viebel/klipse">klipse
      plugin</a>.
    <p>
    <hr>
    ${body}
  </body>
</html>`)
